### ISSUE TITLE
reload script...

### ISSUE THREAD

**Issue by AndyW999** [AcuGIS/OpenNameSearch#2]
Hi David

I tried to add another pbf but it broke everything - please see attached file.

Thanks

Andy.
[OpenNameSearch - Reload.txt](https://github.com/AcuGIS/OpenNameSearch/files/1123999/OpenNameSearch.-.Reload.txt)

**Comment by DavidGhedini** [comment]
Hi Andy -
Does these directories exist on your server?
-su: line 1: cd: /home/ntim/nominatim-2.5.1: No such file or directory
-su: line 3: ./utils/setup.php: No such file or directory
David

**Comment by lsimedia** [comment]
Hi David and Andy,

I think that it is because of a typo in "reload-OpenNameSearch.sh" script.

After running OpenNameSearch.sh script, you will get a folder "**N**ominatim-2.5.1" (not **n**ominatim-2.5.1).

So you can edit "reload-OpenNameSearch.sh" and change, at line 40:
cd /home/${NM_USER}/**n**ominatim-${NM_VER}
by
cd /home/${NM_USER}/**N**ominatim-${NM_VER}

Best regards

PS: David, thank you for your great OpenTileServer and OpenNameSearch scripts !!!

**Comment by DavidGhedini** [comment]
Hi lsimedia and Andy -
Thank you for finding this and sorry for the grief over the typo.
Ill get it updated now
Thanks,
David
